### ISSUE TITLE
pud.h uses C++ keyword "private"

### ISSUE THREAD

**Issue by GitAnonymous** [war2/war2tools#3]
It is currently not possible to use war2tools within a C++ project since the structure "Pud" in pud.h contains the following field:

`Pud_Private *private; /**< Internals, private and opaque data. Don't touch ;-) */ `

Simple fix that works is:

`Pud_Private *private_; /**< Internals, private and opaque data. Don't touch ;-) */ `

**Comment by jeanguyomarch** [comment]
Good catch! Thanks.
