### ISSUE TITLE
PUD_ICON_REPAIR is missing in pud.h

### ISSUE THREAD

**Issue by GitAnonymous** [war2/war2tools#5]
Currently pud.h looks like this:

PUD_ICON_HUMAN_MOVE                           = 83,
PUD_ICON_ORC_MOVE                             = 84,
/* Icon 85 is invalid */
PUD_ICON_COLLECT                              = 86,
PUD_ICON_BUILD_STAGE_1                        = 87,

However, icon 85 is perfectly valid:

<img width="264" alt="icon repair" src="https://github.com/war2/war2tools/assets/8426321/bb0c782a-6c1c-45e6-8b1c-01f80d1cc0fd">

Proposal:

   PUD_ICON_HUMAN_MOVE                           = 83,
   PUD_ICON_ORC_MOVE                             = 84,
   PUD_ICON_REPAIR                               = 85,
   PUD_ICON_COLLECT                              = 86,
   PUD_ICON_BUILD_STAGE_1                        = 87,

I tested this in my project and the icon appears as desired

**Comment by jeanguyomarch** [comment]
Thanks, I'll have a look :+1:
