### ISSUE TITLE
pud.h: PUD_ICON_DEATH_COIL and PUD_ICON_DEATH_AND_DECAY are mixed up

### ISSUE THREAD

**Issue by GitAnonymous** [war2/war2tools#6]
I realized that the death coil and death and decay icon ids are mixed up:

PUD_ICON_BLOODLUST                            = 112,
PUD_ICON_RAISE_DEAD                           = 114,
**PUD_ICON_DEATH_COIL                           = 103,**
PUD_ICON_WHIRLWIND                            = 104,
PUD_ICON_HASTE                                = 96,
PUD_ICON_UNHOLY_ARMOR                         = 98,
PUD_ICON_RUNES                                = 97,
**PUD_ICON_DEATH_AND_DECAY                      = 108,**

should be

PUD_ICON_BLOODLUST                            = 112,
PUD_ICON_RAISE_DEAD                           = 114,
**PUD_ICON_DEATH_COIL                           = 108,**
PUD_ICON_WHIRLWIND                            = 104,
PUD_ICON_HASTE                                = 96,
PUD_ICON_UNHOLY_ARMOR                         = 98,
PUD_ICON_RUNES                                = 97,
**PUD_ICON_DEATH_AND_DECAY                      = 103,**

It would be nice if this could be verified

**Comment by jeanguyomarch** [comment]
It seems that these two icons are swapped, depending on the version of the game.
I think that it is the Battle Net Edition that introduced this swap. This makes the handling of this specific icon a bit awkward.
