### ISSUE TITLE
"pud_config.h" included in pud.h but does not exist

### ISSUE THREAD

**Issue by hsbgit** [war2/war2tools#7]
I did the following under Ubuntu:

- clone war2tools
- build&install
- when using pud.h as usual inside my project compiler says "cannot find pud_config.h" (line 43 in file pud.h)

There is no pud_config.h, only pud_config.h.in? After deleting line 43 everything compiles and works fine

**Comment by jeanguyomarch** [comment]
Thanks for the report. It seems I pushed too fast last time...
pud_config.h should now be installed in the same directory than `pud.h`.

It is not very useful though, as it was introduced to help with lua bindings (that are work-in-progress).
