### ISSUE TITLE
No issue, just a message

### ISSUE THREAD

**Issue by hsbgit** [war2/war2tools#8]
Dear Jean,

as your domain is no longer active this is the only way for me to send you a message.

If you have ever wondered on which project I worked while using your great war2tools lib, have a look here:

https://github.com/hsbgit/war25

I made everything of my project public. It runs on Linux and Windows.  

I wished I would have come further, however, my family and work is blocking me from making much more progress alone. My hope is that other warcraft2 enthusiasts around the world may discover this work and contribute to it.

Feel free to close / delete this isse :) and thanks for your work 🥇

**Comment by jeanguyomarch** [comment]
Hi, thanks for the message, I really appreciate :)
I have not yet taken the time to build and run your project (because I still have to run the wargus extracter ;)), but the screenshots look truly amazing :sparkles: 
I will definitely give it a try soon :+1:
